GRANT SELECT, INSERT, DELETE, UPDATE ON TABLE access_level TO ssbd05mok;
GRANT SELECT, INSERT, DELETE, UPDATE ON TABLE account TO ssbd05mok;
GRANT SELECT, INSERT, DELETE, UPDATE ON TABLE account_data TO ssbd05mok;
GRANT SELECT, INSERT, DELETE, UPDATE ON TABLE admin_data TO ssbd05mok;
GRANT SELECT, INSERT, DELETE, UPDATE ON TABLE manager_data TO ssbd05mok;
GRANT SELECT, INSERT, DELETE, UPDATE ON TABLE owner_data TO ssbd05mok;

GRANT SELECT, UPDATE ON SEQUENCE access_level_id_seq TO ssbd05mok;
GRANT SELECT, UPDATE ON SEQUENCE account_id_seq TO ssbd05mok;

CREATE INDEX access_level_account_id ON access_level USING btree (account);
