package pl.lodz.p.it.ssbd2023.ssbd05.entities.mok;

import lombok.Getter;

@Getter
public enum TokenType {
    REFRESH_TOKEN,
    CONFIRM_REGISTRATION_TOKEN,
    PASSWORD_RESET_TOKEN,
    OVERRIDE_PASSWORD_CHANGE_TOKEN,
    CONFIRM_EMAIL_TOKEN,
    BLOCKED_ACCOUNT_TOKEN,
    TWO_FACTOR_AUTH_TOKEN,
    UNLOCK_ACCOUNT_SELF_TOKEN
}
